name: Deploy us-east-1

on:
  push:
    branches:
      - us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Deploy us-east-1
        run: |
          cd us-east-1
          terraform init
          terraform apply -auto-approve
